name: build code
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: compile
        run: |
           g++ -std=c++11 negarr.cpp proxy.cpp testq1.cpp -o main
      - name: upload main to artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: main
