name: Hello World
on:
  push:
    branches: ["main"]
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello"
      - name: say name
        run: echo "sukanya"
  bye:
    runs-on: ubuntu-latest
    steps:
      - name: say bye
        run: echo "bye"
    
